---

- name: create directory for centos 7
  file: path="{{ tftpbootdir }}centos/x86_64"
        state=directory
        recurse=yes
        owner=root
        group=root
        mode=0755

- name: create pxeconfig dir
  file: path="{{ tftpbootdir }}pxelinux.cfg"
        state=directory
        recurse=yes
        owner=root
        group=root
        mode=0755

- name: copy pxelinux.0 into place
  copy: dest="{{ tftpbootdir }}pxelinux.0"
        src=pxelinux.0
        owner=root
        group=root
        mode=0644

- name: copy menu.c32 into place
  copy: dest="{{ tftpbootdir }}menu.c32"
        src=menu.c32
        owner=root
        group=root
        mode=0644

- name: copy vmlinuz into place
  copy: dest="{{ tftpbootdir }}centos/x86_64/vmlinuz"
        src=vmlinuz
        owner=root
        group=root
        mode=0644

- name: copy initrd.img into place
  copy: dest="{{ tftpbootdir }}centos/x86_64/initrd.img"
        src=initrd.img
        owner=root
        group=root
        mode=0644

- name: copy upgrade.img into place
  copy: dest="{{ tftpbootdir }}centos/x86_64/upgrade.img"
        src=upgrade.img
        owner=root
        group=root
        mode=0644

- name: open tftpboot port 69 on the firewall
  command: iptables -A INPUT -p udp --dport 69 -j ACCEPT
