---

- name: ensure we have a .repo directory
  file: dest={{a_repo_dir}}
        state=directory

- name: Clone Nerd Fonts
  git: clone=yes
       dest="{{a_repo_dir}}/nerd-fonts"
       repo=https://github.com/ryanoasis/nerd-fonts.git
       version='v0.8.0'
       update=no
  register: result

- name: Install Nerd Fonts
  shell: "./install.sh"
  args:
    chdir: "{{a_repo_dir}}/nerd-fonts"
  when: result is changed
