---

- include: "{{ansible_pkg_mgr}}.yml"

- name: add tor user
  user: name={{a_tor_user}}
        state=present
  become: true
  become_user: root

- name: Add tor config dir
  file: dest=/etc/tor
        state=directory
        mode=0755
        owner={{a_tor_user}}
  become: true
  become_user: root

- name: add tor config
  template: dest=/etc/tor/torrc
            src=torrc.j2
            mode=0644
            owner={{a_tor_user}}
            validate="/usr/bin/tor --verify-config -f %s"
  become: true
  become_user: root
  notify: restart tor

- name: Enable tor
  service: name=tor
           enabled=yes
           state=started
  become: true
  become_user: root
