---

- name: Install nginx
  yum: name=nginx
       state=present
  when: ansible_pkg_mgr == 'yum'

- name: Add firewall rules for port 80
  command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT

- name: Add firewall rules for port 443
  command: iptables -A INPUT -p tcp --dport 443 -j ACCEPT
