---

- name: create repo sync script
  template: dest=/usr/local/bin/repo-sync-{{ item.os_name }}-{{ item.os_version }}.sh
            src=repo-sync.sh.j2
            mode=0755
            owner=root
            group=root
  with_items: repos

- name: create cron entry for repo sync scripts
  cron: name="sync {{ item.os_name }}-{{ item.os_version }}"
        minute=00
        hour=01
        day=*
        month=*
        weekday=6
        user=root
        state=present
        job=/usr/local/bin/repo-sync-{{ item.os_name }}-{{ item.os_version }}.sh
  with_items: repos
