---

- name: ensure ssh dir exists
  file: dest={{a_ssh_user_dir}}
        mode=0700
        state=directory

- name: create user ssh config
  template: dest={{a_ssh_user_conf}}
            src=user_config.j2
            mode=0600
