---

- name: Installing zsh
  portage: changed_use=yes
           deep=yes
           newuse=yes
           noreplace=yes
           package="app-shells/zsh"
           state=present
           update=yes
  when: ansible_pkg_mgr  == "portage"
  become: True
  become_user: root

- name: Installing Zsh
  apt: name=zsh
       state=latest
  when: ansible_pkg_mgr  == "apt"
  become: True
  become_user: root

- name: Installing ack (required for some rc files)
  apt: name=ack-grep
       state=latest
  when: ansible_pkg_mgr  == "apt"
  become: True
  become_user: root
