---

- include: install.yml

- name: create tmux directory
  file: dest={{tmux_dir}}
        mode=0755
        state=directory

- name: Adding tmux submodules
  git: clone=yes
       dest={{tmux_dir}}/plugins/{{item|basename}}
       repo={{item}}
       update=yes
  with_items: tmux_submodules

- name: Add main tmux config
  template: dest=~/.tmux.conf
            src=tmux.conf.j2
            mode=0644

- name: Add supplemental tmux configs
  template: dest={{tmux_dir}}/{{item}}
            src={{item}}.j2
            mode=0644
  with_items: tmux_confs
