---

- name: Add EBS volume to owncloud server
  ec2_vol:
    instance: "{{ item.id }}"
    name: {{ a_ebs_volumes_name }}
    volume_type: {{ a_ebs_volumes_type }}
    volume_size: {{ a_ebs_volumes_size }}
    region: {{ a_ebs_volumes_region }}
    delete_on_termination: no
  with_items: ec2.instance
