---

- name: Add konsole rc file
  template: dest={{a_kde_config_dir}}/konsolerc
            src=konsolerc.j2

- name: Ensure konsole apps dir exists
  file: dest={{a_kde_apps_dir}}/konsole
        state=directory

- name: Add konsole shell profile
  template: dest={{a_kde_apps_dir}}/konsole/Shell.profile
            src=Shell.profile.j2
