--- 
- name: Edit konsolerc
  ini_file: dest={{a_kde_config_dir}}/konsolerc
            section={{ item.section }}
            option={{ item.key }}
            value={{ item.value }}
  with_items: "{{ a_kde_konsolerc }}"

- name: replace spaces in konsolerc
  replace: dest={{a_kde_config_dir}}/konsolerc
           regexp=' = '
           replace='='

- name: Ensure konsole apps dir exists
  file: dest={{a_kde_apps_dir}}/konsole
        state=directory

- name: Add konsole shell profile
  ini_file: dest={{a_kde_apps_dir}}/konsole/peteches.profile
            section={{item.section}}
            option={{item.key}}
            value={{item.value}}
  with_items: "{{ a_kde_konsole_shell_profile }}"

- name: replace spaces in konsolerc
  replace: dest={{a_kde_apps_dir}}/konsole/peteches.profile
           regexp=' = '
           replace='='
