---

- name: Installing vim
  apt: name=vim
       state=latest
  become: True
  become_user: root

- name: Installing packages required for some plugins
  apt: name={{item[ansible_pkg_mgr]}}
       state=present
  with_items: vim_plugin_deps.apt
  become: True
  become_user: root


