---

- name: Installing vim
  homebrew: name=vim
            state=latest

- name: Installing packages required for some plugins
  homebrew: name={{item}}
            state=present
  with_items: "{{ vim_plugin_deps.homebrew }}"

- name: Installing packages required for some plugins
  pip: name={{item}}
            state=present
  with_items: "{{vim_plugin_deps.pip}}"
  become: True
  become_user: root
