---

- name: find pip executable
  shell: which pip3 || which pip
  register: pipbin

- name: Installing packages required for some plugins
  pip: name={{item}}
            state=present
            executable="{{pipbin.stdout}}"
  with_items: "{{vim_plugin_deps.pip}}"
