---

- name: create Profile Dir
  file: path={{a_firefox_profile_dir}}
        state=directory

- name: Mark all other profiles as not default.
  lineinfile: dest={{a_firefox_config_dir}}/profiles.ini
              regexp="Default=1"
              state=absent
  when: a_firefox_profile_default == 1

- name: Add Profile to profiles.ini
  ini_file: dest={{a_firefox_config_dir}}/profiles.ini
            section=Profile0
            backup=true
            option={{item.key}}
            value={{item.value}}
  with_dict: a_firefox_profile_ini_opts

- name: remove whitespace around = in profiles.ini
  replace: dest={{a_firefox_config_dir}}/profiles.ini
           regexp=" = "
           replace="="

- name: Add extension dir
  file: dest={{a_firefox_profile_dir}}/extensions/
        state=directory

- name: Add extensions
  copy: dest={{a_firefox_profile_dir}}/extensions/{{item}}
        src=extensions/{{item}}
  with_items: a_firefox_extensions

- name: install extensions
  shell: firefox {{a_firefox_profile_dir}}/extensions/*

- name: Add about:config opts for firefox
  template: dest={{a_firefox_profile_dir}}/user.js
            src=user.js.j2
  with_dict: a_firefox_user_prefs
