---

- name: create Profile Dir
  file: path={{a_firefox_profile_dir}}
        state=directory

- name: Mark all other profiles as not default.
  lineinfile: dest={{a_firefox_config_dir}}/profiles.ini
              regexp="Default=1"
              state=absent
  when: a_firefox_profile_default == 1

- name: Add Profile to profiles.ini
  ini_file: dest={{a_firefox_config_dir}}/profiles.ini
            section=Profile0
            option={{item.key}}
            value={{item.value}}
  with_dict: a_firefox_profile_ini_opts

- name: remove whitespace around = in profiles.ini
  replace: dest={{a_firefox_config_dir}}/profiles.ini
           regexp=" = "
           replace="="

- name: Add about:config opts for firefox
  template: dest={{a_firefox_profile_dir}}/user.js
            src=user.js.j2

- name: Add extensions
  copy: dest={{a_firefox_profile_dir}}/
        src=extensions

- name: Create extension dir for unpacked extensions
  file: dest={{a_firefox_profile_dir}}/extensions/{{item}}
        state=directory
  with_items: a_firefox_extensions_to_unpack

- name: Extract xpi incompatible extensions
  unarchive: copy=no
             creates={{a_firefox_profile_dir}}/extensions/{{item}}/install.rdf
             dest={{a_firefox_profile_dir}}/extensions/{{item}}
             src={{a_firefox_profile_dir}}/extensions/{{item}}.xpi
  with_items: a_firefox_extensions_to_unpack

- name: Remove archive for unpacked extensions
  file: dest={{a_firefox_profile_dir}}/extensions/{{item}}.xpi
        state=absent
  with_items: a_firefox_extensions_to_unpack

