---
- name: find pip executable
  shell: which pip3 || which pip
  register: pipbin

- name: Install generic useful packages
  pip: name={{a_workstation_packages.pip}}
       state=latest
       executable="{{pipbin.stdout}}"
  when: a_workstation_packages.pip
