---

- name: create user systemd default.target.wants
  file: dest={{systemd_user_default_wants_dir}}
        state=directory

- name: Add ssh-agent user service file
  copy: dest={{systemd_user_dir}}/ssh-agent.service
        src=ssh-agent.service

- name: Enabling ssh-agent user service
  file: dest={{systemd_user_default_wants_dir}}/ssh-agent.service
        src={{systemd_user_dir}}/ssh-agent.service
        state=link
