---

- name: Launch EC2 instances
  ec2:
    image: "{{ item.ami }}"
    instance_type: "{{ item.type }}"
    exact_count: "{{ item.count }}"
    count_tag: "{{ item.count_tags }}"
    instance_tags: "{{ item.instance_tags }}"
    profile: "{{ item.boto_profile|default('omit') }}"
    wait: yes
    region: "{{ item.region }}"
    group: "{{ item.security_groups }}"
  with_items: "{{ a_ec2_instances }}"
  register: ec2

- name: Add new hosts to hostgroup
  add_host: hostname={{ item.public_ip }}
            groupname={{a_ec2_instances_groupname}}
  with_items: ec2.instances

- name: wait for ssh to come up
  wait_for: host={{item.public_dns_name }}
            port=24
            delay=60
            timeout=320
            state=started
  with_items: ec2.instances


- debug: var=groups[{{a_ec2_instances_groupname}}]
