function Stream(b,d){b instanceof Stream?(this.enc=b.enc,this.pos=b.pos):(this.enc=b,this.pos=d)}Stream.prototype.get=function(b){void 0==b&&(b=this.pos++);if(b>=this.enc.length)throw"Requesting byte offset "+b+" on a stream of length "+this.enc.length;return this.enc[b]};Stream.prototype.hexDigits="0123456789ABCDEF";Stream.prototype.hexByte=function(b){return this.hexDigits.charAt(b>>4&15)+this.hexDigits.charAt(b&15)};
Stream.prototype.hexDump=function(b,d){for(var a="",c=b;c<d;++c)switch(a+=this.hexByte(this.get(c)),c&15){case 7:a+="  ";break;case 15:a+="\n";break;default:a+=" "}return a};Stream.prototype.parseStringISO=function(b,d){for(var a="",c=b;c<d;++c)a+=String.fromCharCode(this.get(c));return a};
Stream.prototype.parseStringUTF=function(b,d){for(var a="",c=0,e=b;e<d;)c=this.get(e++),a=128>c?a+String.fromCharCode(c):191<c&&224>c?a+String.fromCharCode((c&31)<<6|this.get(e++)&63):a+String.fromCharCode((c&15)<<12|(this.get(e++)&63)<<6|this.get(e++)&63);return a};Stream.prototype.reTime=/^((?:1[89]|2\d)?\d\d)(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])([01]\d|2[0-3])(?:([0-5]\d)(?:([0-5]\d)(?:[.,](\d{1,3}))?)?)?(Z|[-+](?:[0]\d|1[0-2])([0-5]\d)?)?$/;
Stream.prototype.parseTime=function(b,d){var a=this.parseStringISO(b,d),c=this.reTime.exec(a);if(!c)return"Unrecognized time: "+a;a=c[1]+"-"+c[2]+"-"+c[3]+" "+c[4];c[5]&&(a+=":"+c[5],c[6]&&(a+=":"+c[6],c[7]&&(a+="."+c[7])));c[8]&&(a+=" UTC","Z"!=c[8]&&(a+=c[8],c[9]&&(a+=":"+c[9])));return a};Stream.prototype.parseInteger=function(b,d){var a=d-b;if(4<a){var a=a<<3,c=this.get(b);if(0==c)a-=8;else for(;128>c;)c<<=1,--a;return"("+a+" bit)"}a=0;for(c=b;c<d;++c)a=a<<8|this.get(c);return a};
Stream.prototype.parseBitString=function(b,d){var a=this.get(b),c=(d-b-1<<3)-a,e="("+c+" bit)";if(20>=c)for(var f=a,e=e+" ",a=d-1;a>b;--a){for(c=this.get(a);8>f;++f)e+=c>>f&1?"1":"0";f=0}return e};Stream.prototype.parseOctetString=function(b,d){var a=d-b,c="("+a+" byte) ";20<a&&(d=b+20);for(var e=b;e<d;++e)c+=this.hexByte(this.get(e));20<a&&(c+=String.fromCharCode(8230));return c};
Stream.prototype.parseOID=function(b,d){for(var a,c=0,e=0,f=b;f<d;++f){var g=this.get(f),c=c<<7|g&127,e=e+7;g&128||(a=void 0==a?parseInt(c/40)+"."+c%40:a+("."+(31<=e?"bigint":c)),c=e=0);a+=String.fromCharCode()}return a};function ASN1(b,d,a,c,e){this.stream=b;this.header=d;this.length=a;this.tag=c;this.sub=e}
ASN1.prototype.typeName=function(){if(void 0==this.tag)return"unknown";var b=this.tag&31;switch(this.tag>>6){case 0:switch(b){case 0:return"EOC";case 1:return"BOOLEAN";case 2:return"INTEGER";case 3:return"BIT_STRING";case 4:return"OCTET_STRING";case 5:return"NULL";case 6:return"OBJECT_IDENTIFIER";case 7:return"ObjectDescriptor";case 8:return"EXTERNAL";case 9:return"REAL";case 10:return"ENUMERATED";case 11:return"EMBEDDED_PDV";case 12:return"UTF8String";case 16:return"SEQUENCE";case 17:return"SET";
case 18:return"NumericString";case 19:return"PrintableString";case 20:return"TeletexString";case 21:return"VideotexString";case 22:return"IA5String";case 23:return"UTCTime";case 24:return"GeneralizedTime";case 25:return"GraphicString";case 26:return"VisibleString";case 27:return"GeneralString";case 28:return"UniversalString";case 30:return"BMPString";default:return"Universal_"+b.toString(16)}case 1:return"Application_"+b.toString(16);case 2:return"["+b+"]";case 3:return"Private_"+b.toString(16)}};
ASN1.prototype.content=function(){if(void 0==this.tag)return null;if(0!=this.tag>>6)return null==this.sub?null:"("+this.sub.length+")";var b=this.tag&31,d=this.posContent(),a=Math.abs(this.length);switch(b){case 1:return 0==this.stream.get(d)?"false":"true";case 2:return this.stream.parseInteger(d,d+a);case 3:return this.sub?"("+this.sub.length+" elem)":this.stream.parseBitString(d,d+a);case 4:return this.sub?"("+this.sub.length+" elem)":this.stream.parseOctetString(d,d+a);case 6:return this.stream.parseOID(d,
d+a);case 16:case 17:return"("+this.sub.length+" elem)";case 12:return this.stream.parseStringUTF(d,d+a);case 18:case 19:case 20:case 21:case 22:case 26:return this.stream.parseStringISO(d,d+a);case 23:case 24:return this.stream.parseTime(d,d+a)}return null};ASN1.prototype.toString=function(){return this.typeName()+"@"+this.stream.pos+"[header:"+this.header+",length:"+this.length+",sub:"+(null==this.sub?"null":this.sub.length)+"]"};
ASN1.prototype.print=function(b){void 0==b&&(b="");document.writeln(b+this);if(null!=this.sub){b+="  ";for(var d=0,a=this.sub.length;d<a;++d)this.sub[d].print(b)}};
ASN1.prototype.toPrettyString=function(b){void 0==b&&(b="");var d=b+this.typeName()+" @"+this.stream.pos,d=d+("+"+this.header);0<=this.length&&(d+="+");d+=this.length;if(this.tag&32)d+=" (constructed)";else if((3==this.tag||4==this.tag)&&null!=this.sub)d+=" (encapsulates)";d+="\n";if(null!=this.sub){b+="  ";for(var a=0,c=this.sub.length;a<c;++a)d+=this.sub[a].toPrettyString(b)}return d};
ASN1.prototype.toDOM=function(){var b=document.createElement("div");b.className="node";b.asn1=this;var d=document.createElement("div");d.className="head";var a=this.typeName().replace(/_/g," ");d.innerHTML=a;var c=this.content();null!=c&&(c=String(c).replace(/</g,"&lt;"),a=document.createElement("span"),a.className="preview",a.innerHTML=c,d.appendChild(a));b.appendChild(d);this.node=b;this.head=d;var e=document.createElement("div");e.className="value";a="Offset: "+this.stream.pos+"<br/>";a+="Length: "+
this.header+"+";a=0<=this.length?a+this.length:a+(-this.length+" (undefined)");if(this.tag&32)a+="<br/>(constructed)";else if((3==this.tag||4==this.tag)&&null!=this.sub)a+="<br/>(encapsulates)";if(null!=c&&(a+="<br/>Value:<br/><b>"+c+"</b>","object"==typeof oids&&6==this.tag&&(c=oids[c])))c.d&&(a+="<br/>"+c.d),c.c&&(a+="<br/>"+c.c),c.w&&(a+="<br/>(warning!)");e.innerHTML=a;b.appendChild(e);a=document.createElement("div");a.className="sub";if(null!=this.sub){c=0;for(e=this.sub.length;c<e;++c)a.appendChild(this.sub[c].toDOM())}b.appendChild(a);
d.switchNode=b;d.onclick=function(){var a=this.switchNode;a.className="node collapsed"==a.className?"node":"node collapsed"};return b};ASN1.prototype.posStart=function(){return this.stream.pos};ASN1.prototype.posContent=function(){return this.stream.pos+this.header};ASN1.prototype.posEnd=function(){return this.stream.pos+this.header+Math.abs(this.length)};ASN1.prototype.fakeHover=function(b){this.node.className+=" hover";b&&(this.head.className+=" hover")};
ASN1.prototype.fakeOut=function(b){var d=/ ?hover/;this.node.className=this.node.className.replace(d,"");b&&(this.head.className=this.head.className.replace(d,""))};ASN1.prototype.toHexDOM_sub=function(b,d,a,c,e){if(!(c>=e)){var f=document.createElement("span");f.className=d;f.appendChild(document.createTextNode(a.hexDump(c,e)));b.appendChild(f)}};
ASN1.prototype.toHexDOM=function(b){var d=document.createElement("span");d.className="hex";void 0==b&&(b=d);this.head.hexNode=d;this.head.onmouseover=function(){this.hexNode.className="hexCurrent"};this.head.onmouseout=function(){this.hexNode.className="hex"};d.asn1=this;d.onmouseover=function(){var a=!b.selected;a&&(b.selected=this.asn1,this.className="hexCurrent");this.asn1.fakeHover(a)};d.onmouseout=function(){var a=b.selected==this.asn1;this.asn1.fakeOut(a);a&&(b.selected=null,this.className=
"hex")};this.toHexDOM_sub(d,"tag",this.stream,this.posStart(),this.posStart()+1);this.toHexDOM_sub(d,0<=this.length?"dlen":"ulen",this.stream,this.posStart()+1,this.posContent());if(null==this.sub)d.appendChild(document.createTextNode(this.stream.hexDump(this.posContent(),this.posEnd())));else if(0<this.sub.length){var a=this.sub[0],c=this.sub[this.sub.length-1];this.toHexDOM_sub(d,"intro",this.stream,this.posContent(),a.posStart());for(var a=0,e=this.sub.length;a<e;++a)d.appendChild(this.sub[a].toHexDOM(b));
this.toHexDOM_sub(d,"outro",this.stream,c.posEnd(),this.posEnd())}return d};ASN1.decodeLength=function(b){var d=b.get(),a=d&127;if(a==d)return a;if(3<a)throw"Length over 24 bits not supported at position "+(b.pos-1);if(0==a)return-1;for(var c=d=0;c<a;++c)d=d<<8|b.get();return d};ASN1.hasContent=function(b,d,a){if(b&32)return!0;if(3>b||4<b)return!1;var c=new Stream(a);3==b&&c.get();if(c.get()>>6&1)return!1;try{var e=ASN1.decodeLength(c);return c.pos-a.pos+e==d}catch(f){return!1}};
ASN1.decode=function(b){b instanceof Stream||(b=new Stream(b,0));var d=new Stream(b),a=b.get(),c=ASN1.decodeLength(b),e=b.pos-d.pos,f=null;if(ASN1.hasContent(a,c,b)){var g=b.pos;3==a&&b.get();f=[];if(0<=c){for(var h=g+c;b.pos<h;)f[f.length]=ASN1.decode(b);if(b.pos!=h)throw"Content size is not correct for container starting at offset "+g;}else try{for(;;){h=ASN1.decode(b);if(0==h.tag)break;f[f.length]=h}c=g-b.pos}catch(j){throw"Exception while decoding undefined length content: "+j;}}else b.pos+=c;
return new ASN1(d,e,c,a,f)};ASN1.test=function(){for(var b=[{value:[39],expected:39},{value:[129,201],expected:201},{value:[131,254,220,186],expected:16702650}],d=0,a=b.length;d<a;++d){var c=new Stream(b[d].value,0),c=ASN1.decodeLength(c);c!=b[d].expected&&document.write("In test["+d+"] expected "+b[d].expected+" got "+c+"\n")}};
